import { Contact } from './types';

export const SPECIALTIES = [
  'Cardiology',
  'Dermatology',
  'Endocrinology',
  'Gastroenterology',
  'Neurology',
  'Oncology',
  'Ophthalmology',
  'Orthopedics',
  'Pediatrics',
  'Psychiatry',
  'Pulmonology',
  'Radiology',
  'Urology',
  'Other',
];

export const SPECIALTY_COLORS: Record<string, string> = {
  Cardiology: '#E53E3E',
  Dermatology: '#D69E2E',
  Endocrinology: '#38A169',
  Gastroenterology: '#DD6B20',
  Neurology: '#3182CE',
  Oncology: '#805AD5',
  Ophthalmology: '#00B5D8',
  Orthopedics: '#E53E3E',
  Pediatrics: '#F6AD55',
  Psychiatry: '#9F7AEA',
  Pulmonology: '#4299E1',
  Radiology: '#718096',
  Urology: '#2B6CB0',
  Other: '#4A5568',
};

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: '1',
    name: 'Dr. Sarah Chen',
    specialty: 'Cardiology',
    phone: '(555) 201-3344',
    email: 'schen@heartcare.com',
    company: 'Heart Care Associates',
    notes: 'Excellent with complex cases. Prefers email over phone. Available Tue–Thu.',
    createdAt: '2024-01-10',
  },
  {
    id: '2',
    name: 'Dr. Marcus Reid',
    specialty: 'Neurology',
    phone: '(555) 874-2210',
    email: 'mreid@neuromed.com',
    company: 'NeuroMed Center',
    notes: 'Specialist in movement disorders. Takes referrals on Mondays.',
    createdAt: '2024-02-14',
  },
  {
    id: '3',
    name: 'Dr. Priya Kapoor',
    specialty: 'Dermatology',
    phone: '(555) 663-9981',
    email: 'pkapoor@skinclinic.com',
    company: 'Clear Skin Clinic',
    notes: 'Focus on pediatric dermatology. Great bedside manner.',
    createdAt: '2024-03-05',
  },
  {
    id: '4',
    name: 'Dr. James Thornton',
    specialty: 'Cardiology',
    phone: '(555) 449-7723',
    email: 'jthornton@citymed.com',
    company: 'City Medical Group',
    notes: 'Interventional cardiologist. Quick to respond. Good for urgent referrals.',
    createdAt: '2024-03-20',
  },
  {
    id: '5',
    name: 'Dr. Aisha Mwangi',
    specialty: 'Psychiatry',
    phone: '(555) 322-5567',
    email: 'amwangi@mindhealth.com',
    company: 'Mind Health Partners',
    notes: 'CBT specialist. Accepts new patients in Q3.',
    createdAt: '2024-04-01',
  },
  {
    id: '6',
    name: 'Dr. Leo Fernandez',
    specialty: 'Orthopedics',
    phone: '(555) 781-4490',
    email: 'lfernandez@boneandjoints.com',
    company: 'Bone & Joint Institute',
    notes: 'Sports medicine background. Quick surgical consults available.',
    createdAt: '2024-04-15',
  },
];
